# Generated by Django 3.1.13 on 2021-08-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Amount to be paid for the followiing action.', null=True, verbose_name='Amount to be paid')),
                ('ref', models.CharField(help_text='Reference number of the the above payment', max_length=50, null=True, verbose_name='Payment Reference Number')),
                ('email', models.EmailField(help_text='Email address of the customer', max_length=254, null=True, verbose_name='Email of the customer')),
                ('verified', models.BooleanField(default=False, help_text='Verified payment status to identify if the payment is been verified by the payment gateway or not.', null=True, verbose_name='Verified Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='the date when the payment was taken place.', verbose_name='Date of the payment')),
            ],
            options={
                'verbose_name': 'All Payment',
                'verbose_name_plural': 'All Payment',
                'ordering': ['-date_created'],
            },
        ),
    ]
