# Generated by Django 3.1.13 on 2021-08-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(help_text='Reference number of the the above payment', max_length=500, null=True, verbose_name='Payment Reference Number'),
        ),
    ]
